#+title: Computer Security
#+SETUPFILE: /home/praaneshnair/.config/doom/templates/org/html-preamble.org

* Introduction

** Types of Security
*** Computer Security
- It is designed to protect data which is stored in a device with the help of
  tools.

*** Network Security
- It is designed to protect data during transmission using LAN, WAN.

*** Internet Security
- It is designed to protect data during their transmission over an
  interconnected network.
  
** What is an information system?
- Any form of hardware or software used to store information.
- It consists of computing resources (processor, memory, RAM, etc), data,
  processes, software.


** Who is an intruder?
Anyone who tries to get unauthorized access of an information system.

* CIA Triad: What is Computer Security? 
- The protection provided to an automated information system in order to attain
  the applicable objectives of preserving the *confidentiality*, *integrity* and
  *availability* of information system resources.

** Confidentiality
- This is the *protection of information* from *unauthorized disclosure*.
- Give authorization to access data.
- Confidentiality covers two concepts:
  
*** Data Confidentiality
- Confidentiality tells us that if you have the authorization, you can access
  data.
- An attack on confidentiality could be, for instance "John copying Mary's
  assignment". Mary's work was exposed to an unauthorized party.

*** Privacy
- Privacy tells us that even if you are authorized, you may not be able to
  access all of the data.

*** Authentication
- This ensures that someone's identify is verified.
- An example of an attack on authentication could be, "Henry spoofs Julie's IP
  address to gain access to her computer".

** Integrity
- This is the *protection of information* from *unauthorized modification*.
- The data you store and the data you retrieve should be the same: it shouldn't
  be manipulated or destroyed in the process.
- Again, integrity covers two concepts:

*** Data Integrity
- The data in a database should be complete and consistent.

*** System Integrity
- The information system should not be tamper-able.
- For example, an ATM machine should have system integrity. Data integrity
  should be ensured in the bank account.
- An attack on integrity could be "Carol changes Mary's cheque from $100 to
  $1000".

** Availability
- The data should be available without any hurdles.

* Three Aspects of Information Security

** Security Attack
- Actions which compromise on security information.
- It is an assualt on system security that derives from an intelligent threat.

*** Security Threat
- It's a potential danger that might exploit vulnerability.

*** Two types of Attacks

**** Active Attack
- An attacker tries to modify the content of the messages.
- The data stream is directly modified. 
- This is a threat for System Integrity and Availability.
- You can't prevent an active attack. You (the victim) get to know about it only
  after the content of the messages is modified.
- Here, the result is an actual damaged system. 
- A simpler example would be "Gina forging Roger's signature", as this is an act
  of data fabrication.
- Here's another example: "Henry spoofs Julie's IP address to gain access to her
  computer"

***** Masquerade (pronounced mask-er-ade)
- Pretending to be someone else
- It literally refers to a party where people wear masks.

***** Replay
Retransmitting valid data

***** Modification of Messages
Modifying messages before they reach the target.

***** Denial of Service
Making a system unavailable to users by flooding it with traffic.



**** Passive Attack
- An attacker observes the messages, and uses them for malicious purposes
  information.
- Here, the data stream is just monitored, not modified.
- This is a threat for Confidentiality.
- You can prevent and detect a passive attack. A passive attack becomes an
  active attack when data is modified. 
- You (the victim) won't get to know if the attack happened.
- The result is not a damaged system. 
- Examples include snooping and sniffing. Eavesdropping is a generalized term
  that means listening to/intercepting communication. Sniffing is a type of
  eavesdropping.
  
  | Term     | Meaning                                      |
  |----------+----------------------------------------------|
  | Sniffing | Using software (sniffers) to capture packets |
  | Snooping | Observing screens, keystrokes, or files      |
  
- Here's an example of a passive attack: "John copies Mary's assignment". The
  assignment wasn't changed - it's an act of eavesdropping.

  
** Security Service
- It is intended to counter security attacks by using security mechanisms.
- It replicates functions normally associated with physical documents.
- Services are essentially the desired outcomes (essentially the CIA triad) of a
  protected system.

*** Definitions by different standards

**** X.800
- It's a 

***** Authentication

***** Access Control (Data Privacy)

***** Confidentiality

***** Data Integrity

***** Non-Repudiation (Rejection)
- Protection against Denial of Service.

*** Notorization
- It's an official witness for signing a document. The person/body who does this
  is called a notary.

** Security Mechanism
- These are HOW to counter security attacks (detect one, or recover from one).
- They involve the tools/methods like cryptography or key-establishments.

* OSI Security Architecture
- It's a standard framework of 

* Models for the Security of Network
There are two models for security of networks

** Model for Network Security
- The sender passes *secret information* (key) as an argument, and runs a
  *security-related transformation* (encryption) on the message.
- The output of this is an encrypted message.
- This encrypted message passes through an *information channel* which is open to
  anyone and absolutely any passive attack.
- The reciever passes *secret information* (key) as an argument, and runs a
  *security-related transformation* (decryption) on the encrypted message and gets
  back the original message.
- The keys and the information channel is provided by a *trusted third party*.

  file:/home/praaneshnair/gitProjects/org-notes/computer-security/network_security.png

** Model for Network Access Security
- This model requires to select an appropriate *gatekeeper function* to identify
  the user of an information system.
- The gatekeeper function is a security checkpoint which decides who can enter
  and what actions are allowed.
- Even after entry to the system, security continues to provide role-based
  *access control*, *file-permissions*, and *login*.

*** Types of attacks on access controls

**** Brute-Force Attacks
- You keep trying all combinations of characters in all possible lengths, until
  you actually crack the password.

**** Dictionary Attacks
 - Guessing passwords from a predefined dictionary of common words, phrases and
   passwords,

*** Layered Security Tools/Devices


| Firewall                                                                                                        | IPS                                                                                                                                 | IDS                                                                                                                                       |
|-----------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------|
| It's a network security device that filters incoming and outgoing traffic based on IP address and port numbers. | Intrusion Prevention System is a network security device that detects, inspects the contents of the packets and classifies traffic. | Intrusion Detection System is a network security device or software that monitors traffic for malicious activity and alerts on detection. |
| This should be the first line of defence.                                                                       | Should be placed after firewall.                                                                                                    | Should be placed after firewall.                                                                                                          |
| Blocks traffic.                                                                                                 | Prevents traffic when anomaly is detected.                                                                                          | Alerts on detection of anomaly.                                                                                                           |




*** Zero-Day Attack
- It's an attack that can happen at any point of time, without any prior signs.
- Zero-day attack happens when a malicious actor uses a zero-day attack to plant
  malware.

* Malicious Program

** Host Dependent Malicious Programs

*** Virus
- It's a malicious program that replicates itself and spread across the files of
  the same system.
*** Trojan Horse
- These are malware that are disguised as legitimate programs/softwares to trick
  the users into installing them.
*** Trapdoors/Backdoor
- Malware which enter using undocumented entry points.
*** Logic Bomb
- Malware that remain inactive until some conditions are met.

** Host independent Malicious Programs

*** Worms
- It's a malicious program that replicates itself (just like viruses), but they
  spread across different systems.
- The first worm in the world is called the *Morris Worm*, and was released in
  November 1988 by Robert Morris (Not Robert Worm).

*** Zombie
- It takes control of an entire system.
- Zombies replicate too.

* Cryptography

** Basic Terminology

| Word          | Meaning                                                       |
|---------------+---------------------------------------------------------------|
| *Plain Text*    | Original Message                                              |
| *Cipher Text*   | Encrypted Message                                             |
| *Cipher*        | Algorithm for encrypting                                      |
| *Key*           | Secret Info, used in Cipher only known to sender and Reciever |
| *Encipher*      | Process of Encrypting                                         |
| *Decipher*      | Process of Decrypting                                         |
| *Cryptography*  | Study of Encryption Principles/Methods                        |
| *Cryptanalysis* | Study of deciphering cipher text, without knowing the key     |
| *Cryptology*    | Field of both cryptography and cryptanalysis                  |

** Types of Cryptography

*** Based on Encryption Techniques

**** Substitution

***** Classical Substitution Cipher
- Every occurrence of a plain text symbol is replaced by a corresponding
  ciphertext character.

****** Ceaser/Shift Cipher
This is the earliest known subsitution cipher.
\[ C_{1} = e(m_{1}) = m_{1} + k\mod(s) \]

******* For example, let m = college, k = 3 and s = 26.

- C_{1}[1] = (position of 'c') + 3mod(26) = f
- C_{1}[2] = (position of 'o') + 3mod(26) = r
- C_{1}[3] = (position of 'l') + 3mod(26) = o
- C_{1}[4] = (position of 'l') + 3mod(26) = o
- C_{1}[5] = (position of 'e') + 3mod(26) = h
- C_{1}[6] = (position of 'g') + 3mod(26) = j
- C_{1}[7] = (position of 'e') + 3mod(26) = h
- Hence, C_{1} = e(college) = froohjh


******* In general, for alphabets, Ceasar Cipher is given as

| *Encryption:* | $E(P) = (P+K)\mod(26)$  |
| *Decryption:* | $D(C) = (C-K)\mod(26)$  |


******* For example, Encrypt KHOOR with k=4
- C_{1}[1] = (position of 'K') + 4mod(26) = O
- C_{1}[2] = (position of 'H') + 4mod(26) = L
- C_{1}[3] = (position of 'O') + 4mod(26) = S
- C_{1}[4] = (position of 'O') + 4mod(26) = S
- C_{1}[5] = (position of 'R') + 4mod(26) = V
- Hence the string is OLSSV


******* Decrypt Ciphertext ABC, k=3
- A: $(0-3)\mod26 = -3\mod(26) = (-3+26)\mod(26) = 23$


******* Code for Encryption
#+begin_src python :results output raw :wrap src :exports both
def encrypt(plaintext: str, k: int, alphabet_size: int):
    encrypted_text = ""
    start = None
    for c in plaintext:
        if ord(c)>=ord('A') and ord(c)<=ord('Z'):
            start = ord('A')
            diff = 0
        elif ord(c)>=ord('a') and ord(c)<=ord('z'):
            start = ord('a')
            diff = 0
        elif ord(c)>=ord('0') and ord(c)<=ord('9'):
            start = ord('0')
            diff = 16
            
        if c!=' ':
            encrypted_text += chr(start+(ord(c)-start+k)%(alphabet_size - diff))
        else:
            encrypted_text += ' '
    print(encrypted_text)
    
encrypt("Hello World3!", 2, 26) 


#+end_src

#+RESULTS:
#+begin_src
Jgnnq Yqtnf57
#+end_src

******* Code for Decryption
#+begin_src python :results output raw :wrap src :exports both
def decrypt(plaintext: str, k: int, alphabet_size: int):
    decrypted_text = ""
    
    for c in plaintext:
        if ord(c)>=ord('A') and ord(c)<=ord('Z'):
            decrypted_text += chr(ord('A')+(ord(c)-ord('A')-k)%alphabet_size)
        elif ord(c)>=ord('a') and ord(c)<=ord('z'):
            decrypted_text += chr(ord('a')+(ord(c)-ord('a')-k)%alphabet_size)
        elif c == ' ':
            decrypted_text += ' '
        elif ord(c)>=ord('0') and ord(c)<=ord('9'):
            decrypted_text += chr(ord('0')+(ord(c)-ord('0')-k)%10)
    print(decrypted_text)
    
decrypt("Jgnnq Yqtnf5", 2, 26) 


#+end_src

#+RESULTS:
#+begin_src
Hello World3
#+end_src

The logic for encryption and decryption is pretty simple:
- You iterate through the characters of the text (say each character is ~c~)
- ~ord(c)-ord('A')~ finds the alphabetic position (0-25)
- Add/Subtract Shift value on this alphabetic position and take modulo alphabet
  size. This value is again between 0 and 25.
- Add the above value to the ASCII value of ~A~, and convert it back into a
  character.


******* Cryptanalysis

******** Break the ciphertext WKLV using cryptanalysis
The program given below is a very simple Python Script to generate all possible
plaintexts for a given ciphertext.
#+begin_src python :results output raw :wrap src :exports both :session ceasar
def breakCaesar(x):
    for k in range(26):
        for c in x.upper():
            shift = (ord(c) - ord('A') - k)%26 
            cipher_char = chr(ord('A')+shift)
            print(cipher_char, end="")
        print(end=", ")
        
breakCaesar("WKLV")

#+end_src

#+RESULTS:
#+begin_src
WKLV, VJKU, UIJT, THIS, SGHR, RFGQ, QEFP, PDEO, OCDN, NBCM, MABL, LZAK, KYZJ, JXYI, IWXH, HVWG, GUVF, FTUE, ESTD, DRSC, CQRB, BPQA, AOPZ, ZNOY, YMNX, XLMW,
#+end_src

*Explanation*: For each alphabet, this is what's happening:
- ~ord(c) - ord('A')~ is basically the difference between the ASCII value of the
  character in the string, and the ASCII value of the letter 'A'. This
  difference is in the range 0-25. ~ord(c) - ord('A')~ is the value of $C$ in
  $D(C) = (C-K)\mod(26)$.
- ~- k~ is doing the $(C-K)$ part in $D(C) = (C-K)\mod(26)$.
- ~% 26~ is doing the $\mod(26)$ part in $D(C) = (C-K)\mod(26)$.
- We add ~ord('A')~ to the shift so that we can convert this number back to ASCII.
- To convert the ASCII value back into a number, we have to typecast it into a
  character, by passing it into the ~chr()~ function.


******** Break the ciphertext GWTBS

#+begin_src python :results output raw :wrap src :exports both :session ceasar
breakCaesar("GWTBS")
#+end_src

#+RESULTS:
#+begin_src
GWTBS, FVSAR, EURZQ, DTQYP, CSPXO, BROWN, AQNVM, ZPMUL, YOLTK, XNKSJ, WMJRI, VLIQH, UKHPG, TJGOF, SIFNE, RHEMD, QGDLC, PFCKB, OEBJA, NDAIZ, MCZHY, LBYGX, KAXFW, JZWEV, IYVDU, HXUCT,
#+end_src



****** Multiplicative Cipher
- Ceasar cipher was the additive cipher.
- Here, for each character plaintext character $p$, the cipher text character
  $c$ is given as:
  
  $$c = (a \times p) \mod(26)$$
  
  where $a$ is the key.
- Decrypting the cipher text is given as:
  $$p = (a^{-1} \times c) \mod(26)$$

| Feature               | Caesar Cipher                                                      | Multiplicative Cipher                      |
|-----------------------+--------------------------------------------------------------------+--------------------------------------------|
| *Encryption*            | \(C = (P + k) \bmod 26\)                                           | \(C = (P \times k) \bmod 26\)                   |
| *Key space*             | 26 possible keys, but \(k=0\) gives no encryption → *25 useful keys* | Only keys *coprime with 26* are valid        |
| *Valid keys*            | \(k = 0,1,\dots,25\)                                                   | \(k \in \{1,3,5,7,9,11,15,17,19,21,23,25\}\) |
| *Number of useful keys* | *25*                                                                 | *12*                                         |
| *Key condition*         | No special restriction                                             | \(\gcd(k,26)=1\)                           |

  
  
****** Affine Cipher
- This is a combination of multiplicative and additive. 
- After doing $(a \times p)$, you also add a second key $b$ before in the modular
  arithmetic expression.
- Encryption is given as:

  $$c = (a \times p + b)\mod(26)$$
- And decryption is:

  $$p = a^{-1}(c - b)\mod(26)$$
- The number of keys (pairs of $(a,b)$) possible are $\phi(26) \times 26 = 12 \times 26 =
  312$ keys. There are 26 keys possible for $b$, and $\phi(26)$ keys possible for
  $a$ because only the numbers coprime with 26 can be used for $a^{-1}\mod(26)$.
  



***** Simple Substitution/ Monoalphabetic
- Rather than shifting the alphabets, you shuffle the alphabets randomly.
- Every plain text letter maps to a random cipher text letter, hence there are
  26 keys.
- Given a ciphertext, there are $26!$ possible plain texts.
- The relative *letter frequencies* never change.

***** Polygram
- A block of plain text symbols is replaced by a corresponding ciphertext block
  of characters.
- Sequence of two plain text characters are known as *digrams*, replaced by other
  digrams.
- For example, the word 
  #+begin_src txt
CO LL EG Ex
  #+end_src
  This can become, say (random, just for example):
  #+begin_src txt
xy ab up ld
  #+end_src

****** Playfair Cipher

******* Explanation
- Make a $5 \times 5$ matrix. In these 25 spaces, you'll have to fill all 26
  alphabets. To accommodate the extra alphabet, we merge I and J in one box, by
  convention.
- You start by filling the alphabets of the keyword given (without repetition).
- After you're done with that, start with the rest of the alphabet, and fill in
  the rest of the gaps in order without repetition.

  

******** Example we'll be using to learn the rules
- keyword: CRYPTOGRAPHY CLASS SPRING

| C | R   | Y | P | T |
| O | G   | A | H | L |
| S | I/J | N | B | D |
| E | F   | K | M | Q |
| U | V   | W | X | Z |



******** How to Encrypt a given plain text

1. If letters of a pair are both same, then add an x after the first letter and
   encrypt the new pair.
   - For example: If you have the word ~H E L L O~, you'd resolve it as:
     #+begin_src txt
HE LX LO
     #+end_src
     and not
     #+begin_src txt
HE LL O
     #+end_src
2. If letters appear on the same row, replace them with the letters to their
   immediate right with wrapping, according to the direction.
   - For example, consider one row of the matrix to be:
     
     | O | G   | A | H | L |

     For ~HA~, the corresponding plain text could be ~LH~ or ~AG~. In our course,
     we'll stick to ~AG~.
     
3. If letters appear on the same column, replace them with the letters
   immediately below, also with wrapping according to the direction.
   - For example, consider one column of the matrix to be:
     
     | Y |    
     | A |
     | N |
     | K |
     | W |

     - For ~NK~, the corresponding plain text would be ~KW~.

     - For ~YW~, the corresponding plain text would be ~AY~.

4. If letters are not on the same row/column, replace them with the letters on
   the same row respectively but add the other pair of corners of the rectangle,
   by the original pair.
   
   

******** Demonstration of the plain text being encrypted
- Consider the plain text "Hello find the solution".
- This will be broken into:
  #+begin_src txt
HE   LX   LO   FI   ND   TH   ES   OL   UT   IO   NZ
  #+end_src
- And the encrypted text will look like:
  #+begin_src txt
OQ   OZ   OG   IG   BS   PL   SO   GO   ZC   SG   DW             
  #+end_src
  



******* Solving another Example
- Keyword: KEYWORD

  | K | E | Y | W   | O |
  | R | D | A | B   | C |
  | F | G | H | I/J | L |
  | M | N | P | Q   | S |
  | T | U | V | X   | Z |

  
******** Plain Text: *Why don't you*
- This will be broken into:
  #+begin_src txt
WH   YD   ON   TY   OU
  #+end_src
- And the encrypted text will look like:
  #+begin_src txt
KL   OR   KS   ZK   KZ
  #+end_src


******** Plain Text: *Come to the window*
- This will be broken into:
  #+begin_src txt
CO   ME   TO   TH   EW   IN   DO   WX
  #+end_src
- And the encrypted text will look like:
  #+begin_src txt
OZ   NK   ZK   VF   YO   GQ   CE   BW
  #+end_src



******* Code for Encryption
#+begin_src python :results output raw :wrap src :exports both
def encrypt(plaintext: str, keyword: str):
    visited = {}
    matrix = [[0]*5 for i in range(5)]
    i = 0
    j = 0
    for c in keyword:
        if c not in visited:
            matrix[i][j] = c
            visited[c] = (i,j)
            if j==4:
                i += 1
                j = 0
            else:
                j += 1
    for x in range(26):
        if chr(ord('A')+x) not in visited:
            visited[chr(ord('A')+x)] = (i,j)
            if chr(ord('A')+x)=='J':
                continue
            matrix[i][j] = chr(ord('A')+x)
            if j==4:
                i += 1
                j = 0
            else:
                j += 1
    if len(plaintext)%2!=0:
        plaintext += 'X'
    for i in range(1, len(plaintext), 2):
        ch1_i = visited[plaintext[i-1]][0]
        ch1_j = visited[plaintext[i-1]][1]
        ch2_i = visited[plaintext[i]][0]
        ch2_j = visited[plaintext[i]][1]

        if ch1_j == ch2_j:
            print(matrix[ch1_i][(ch1_j + 1)%5], end='')
            print(matrix[ch2_i][(ch2_j + 1)%5], end='')
        elif ch1_i == ch2_i:
            print(matrix[(ch1_j + 1)%5][ch1_i], end='')
            print(matrix[(ch2_j + 1)%5][ch2_i], end='')
        else:
            print(matrix[ch1_i][ch2_j], end='')
            print(matrix[ch2_i][ch1_j], end='')
            
        
        
        
encrypt('WHYDONTYOU','KEYWORD')
#+end_src

#+RESULTS:
#+begin_src
YIEAESVKEZ
#+end_src

******* Code for Decryption

#+begin_src python :results output raw :wrap src :exports both

def decrypt(ciphertext: str, keyword: str):
    visited = {}
    matrix = [[0]*5 for i in range(5)]
    i = 0
    j = 0
    for c in keyword:
        if c not in visited:
            matrix[i][j] = c
            visited[c] = (i,j)
            if j==4:
                i += 1
                j = 0
            else:
                j += 1
    for x in range(26):
        if chr(ord('A')+x) not in visited:
            visited[chr(ord('A')+x)] = (i,j)
            if chr(ord('A')+x)=='J':
                continue
            matrix[i][j] = chr(ord('A')+x)
            if j==4:
                i += 1
                j = 0
            else:
                j += 1
    for i in range(1, len(ciphertext), 2):
        ch1_i = visited[ciphertext[i-1]][0]
        ch1_j = visited[ciphertext[i-1]][1]
        ch2_i = visited[ciphertext[i]][0]
        ch2_j = visited[ciphertext[i]][1]

        if ch1_j == ch2_j:
            print(matrix[ch1_i][(ch1_j + 1)%5], end='')
            print(matrix[ch2_i][(ch2_j + 1)%5], end='')
        elif ch1_i == ch2_i:
            print(matrix[(ch1_j - 1)%5][ch1_i], end='')
            print(matrix[(ch2_j - 1)%5][ch2_i], end='')
        else:
            print(matrix[ch1_i][ch2_j], end='')
            print(matrix[ch2_i][ch1_j], end='')

decrypt('YIEAESVKEZ', 'KEYWORD')
            
#+end_src

#+RESULTS:
#+begin_src
WHYDONTYOU
#+end_src

Some things to note in this code are:
- To go through the matrix, maintain separate variables for row and column. If
  the row exceeds 4, reset row to zero, and increase the column value by 1.
- ~visited[c]~ stores the matrix coordinates (~i~ and ~j~) of the character ~c~. In
  other words, the position of a character in the matrix can be obtained as
  ~(visited[c][0], visited[c][1])~.
- Make sure that the plaintext is of even length. If not, pad it with a
  character.
- Once you actually have the matrix, you iterate having a skip value of 2, to pick two characters at a time:
  - If both characters are in the same row, move both forward (modulo 5 of
    coures) by 1 unit. Hence the column is modified.
  - If both characters are in the same column, move both downwards by 1 unit.
    Hence the row is modified.
  - If it is neither of the cases, you swap the columns of both characters.

****** Hill Cipher
Consider the Example: Plaintext = ~CODE~, Key =   $\begin{bmatrix} 3 & 3 \\ 2 & 5  \end{bmatrix}$
******* Encryption
$$\text{Cipher Text} = \begin{bmatrix} \text{Key} \end{bmatrix} \times \text{Plain Text} \mod(26)$$
- Plaintext:
  #+begin_src txt
CO   DE
  #+end_src
  In numeric indices:
  $$\begin{bmatrix} 2  \\ 14  \end{bmatrix} \text{ and }   \begin{bmatrix} 3 \\ 4  \end{bmatrix}$$
- CipherText:
  $$ \begin{bmatrix} 3 & 3 \\ 2 & 5  \end{bmatrix} \times    \begin{bmatrix} 2  \\ 14  \end{bmatrix} \mod(26) = \begin{bmatrix} 22\\ 22 \end{bmatrix}$$
  $$ \begin{bmatrix} 3 & 3 \\ 2 & 5  \end{bmatrix} \times    \begin{bmatrix} 3  \\ 4  \end{bmatrix} \mod(26) = \begin{bmatrix} 21 \\ 0 \end{bmatrix}$$
- In alphabetic form:
  #+begin_src txt
WW   VA
  #+end_src
  
******* Decryption
$$\text{Plain Text} = \begin{bmatrix} \text{Key} \end{bmatrix}^{-1} \times \text{Cipher Text} \mod(26)$$

- $[\frac{1}{\det{k}} \times \text{adj}(k) ] \times \text{(Cipher Text)} \mod(26)$
- $[9^{-1} \times \text{adj}(k) ] \times \text{(Cipher Text)} \mod(26)$
- $[9^{-1} \times  \begin{bmatrix} 5 & -3 \\ -2 & 3  \end{bmatrix} ] \times \text{(Cipher Text)} \mod(26)$
- $[ \begin{bmatrix} 5 & -3 \\ -2 & 3  \end{bmatrix} 9^{-1} \mod(26)] \times \text{(Cipher Text)} \mod(26)$
Refer to [[*Extended Euclidean Algorithm][Extended Euclidean Algorithm]]
- $[ \begin{bmatrix} 5 & -3 \\ -2 & 3  \end{bmatrix} \times 3] \times \text{(Cipher Text)} \mod(26)$
- $[ \begin{bmatrix} 15 & -9 \\ -6 & 9  \end{bmatrix}] \times \begin{bmatrix}22 \\ 22\end{bmatrix} \mod(26) = \begin{bmatrix}2 \\ 14\end{bmatrix}$
- $[ \begin{bmatrix} 15 & -9 \\ -6 & 9  \end{bmatrix}] \times \begin{bmatrix}21 \\ 0\end{bmatrix} \mod(26) =  \begin{bmatrix} 3 \\ 4  \end{bmatrix}$



***** Homophonic
- If a letter $x$ appears for $y\%$ of all characters, we assign $y$ number of
  symbols to represent it.

***** Polyalphabetic
- In Caesar cipher, the key was a single number.
- Polyalphabetic cipher uses a key to select which alphabet is used for each
  alphabet of the message.
- Once the key reaches the end it is repeated from the beginning to match the
  length of the plain text.

****** Vigenere Cipher

******* Encryption
- This is one of the simplest polyalphabetic substitution cipher.
- It is effectively multiple caeser ciphers.
- $K = K_{1} K_{2} K_{3}....K_{L}$, where $L$ is the length of the key.
- The same plain text character is encrypted to different cipher text characters.
- Assume plain text to be "WE ARE DISCOVERED SAVE YOURSELF" and the key to be "DECEPTIVE"
  
  Making the alphabet-index mapping programmatically:
  #+begin_src python :results output raw :exports both
print('|', end='')
for i in range(26):
    print(f'{i} - {chr(ord('A')+i)} |', end='')

  #+end_src

  #+RESULTS:
  | 0 - A | 1 - B | 2 - C | 3 - D | 4 - E | 5 - F | 6 - G | 7 - H | 8 - I | 9 - J | 10 - K | 11 - L | 12 - M | 13 - N | 14 - O | 15 - P | 16 - Q | 17 - R | 18 - S | 19 - T | 20 - U | 21 - V | 22 - W | 23 - X | 24 - Y | 25 - Z |

- We map each alphabet of the plain text to the key repeated as many times as
  required:
  
  #+begin_src txt
W E A R E D I S C O V E R E D S A V E Y O U R S E L F
D E C E P T I V E D E C E P T I V E D E C E P T I V E
_____________________________________________________
Z I C V T W Q N G R Z G V T W A V Z H C Q Y G L M G J
  #+end_src
  
- In Vigenere Cipher the length of the keyword can be found out as two identical
  sequences of plain text letters occur at a distance that is an integer
  multiple of the keyword length will generate identical cipher text sequences.

- Since the periodic nature of the keyword was the issue, Vigenere proposed an
  *autokey system*, in which a keyword is concatenated with the plain text to
  match the length of the plain text.
  
  #+begin_src txt
W E A R E D I S C O V E R E D S A V E Y O U R S E L F
D E C E P T I V E W E A R E D I S C O V E R E D S A V 
_____________________________________________________
  #+end_src


******* Code 

#+begin_src python :results output raw :wrap src :exports both
def encrypt(plaintext: str, key: str):
    j = 0
    for i in range(len(plaintext)):
        print(chr(ord('A') + (ord(list(plaintext)[i]) + ord(list(key)[j]) - 2*ord('A'))%26), end='')
        j = (j+1)%len(key)


def decrypt(ciphertext: str, key: str):
    j = 0
    for i in range(len(ciphertext)):
        print(chr(ord('A') + (ord(list(ciphertext)[i]) - ord(list(key)[j]) - 2*ord('A'))%26), end='')
        j = (j+1)%len(key)

        
encrypt('WEAREDISCOVEREDSAVEYOURSELF', 'DECEPTIVEDECEPTIVEDECEPTIVE')
print()
decrypt('ZICVTWQNGRZGVTWAVZHCQYGLMGJ', 'DECEPTIVEDECEPTIVEDECEPTIVE')
#+end_src

#+RESULTS:
#+begin_src
ZICVTWQNGRZGVTWAVZHCQYGLMGJ
WEAREDISCOVEREDSAVEYOURSELF
#+end_src

******* Cryptanalysis

******** Example 1: Plain Text = "acbxzcb", Cipher Text = "bxbywdb"

|               | ~0~ | ~1~ | ~2~ | ~3~ | ~4~ | ~5~ | ~6~ |
| *Plain Text* \rightarrow  | a | c | b | x | z | c | b |
| *Cipher Text* \rightarrow | b | x | b | y | w | d | b |



****** Vernam Cipher aka. One Time Padding (OTP)
- You perform bitwise XOR on the ASCII value of the characters of the plain text
  and the key.
- Here is the XOR Table:

  | A | B | A XOR B |
  |---+---+---------|
  | 0 | 0 |       0 |
  | 0 | 1 |       1 |
  | 1 | 0 |       1 |
  | 1 | 1 |       0 |
  
- For example:
  |              | String Given | Char-by-char ASCII Value | Char-by-char value in Binary |
  |--------------+--------------+--------------------------+------------------------------|
  | *Plain text* \rightarrow | CAT          |                   676584 |     010000110100000101010100 |
  | *Key* \rightarrow        | DOG          |                   687971 |     010001000100111101000111 |
  |--------------+--------------+--------------------------+------------------------------|
  |              |              |     *Plain Text XOR Key* \rightarrow |     000001110000111000010011 |

- One thing to note is that the key length has to be at least as long as the
  plain text.

- Theoretically, this cipher is impossible to decrypt because the key has to be
  purely random.

  
******* Code

#+begin_src python :results output raw :wrap src :exports both :session labb

def encrypt(plaintext: str, key: str):
    cipher = []
    if len(plaintext) != len(key):
        return False
    for i in range(len(plaintext)):
        cipher.append(chr(ord(plaintext[i]) ^ ord(key[i])))
    return cipher


for x in encrypt('CAT', 'DOG'):
    print(ord(x), end=' ')

print()

# decryption
print(encrypt(encrypt('CAT', 'DOG'), 'DOG'))

#+end_src

#+RESULTS:
#+begin_src
7 14 19 
['C', 'A', 'T']
#+end_src

**** Transposition / Permutation Cipher
- This cipher hides the message by rearranging the letters of the plain text
  without changing the actual letters.

****** Railfence Cipher
******* Encryption
- Here you write message's letters diagonally over the rows, then read the
  message row-by-row.
- For example, plain text = "meet me after the party", and the number of rows
  is 3 (this is the key).

  | m |   |   | t |   |   | a |   |   | e |   |   | h |   |   | a |   |   | y |
  |   | e |   |   | m |   |   | f |   |   | r |   |   | e |   |   | r |   |   |
  |   |   | e |   |   | e |   |   | t |   |   | t |   |   | p |   |   | t |   |
  
- The cipher text would be "mtahaeyemfrereettpt"
******* Decryption
- For example, let the cipher text be "mtahaeyemfrereettpt"
- The length of the text is 18, and the number of rails is 3.
- Find the positions of letters in each rail:
  - *Rail 1:* ~0, 3, 6, 9, 12, 15, 18~
  - *Rail 2:* ~1, 4, 7, 10, 13, 16~
  - *Rail 3:* ~2, 5, 8, 11, 14, 17~
- So the ciphertext is:
  
  | 0 | 3 | 6 | 9 | 12 | 15 | 18 | 1 | 4 | 7 | 10 | 13 | 16 | 2 | 5 | 8 | 11 | 14 | 17 |
  | m | t | a | e |  h |  a |  y | e | m | f |  r |  e |  r | e | e | t |  t |  p |  t |
  
- Now that we've mapped the correct indices, we can find the plain text:
  
  | 0 | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | 10 | 11 | 12 | 13 | 14 | 15 | 16 | 17 | 18 |
  | m | e | e | t | m | e | a | f | t | e |  r |  t |  h |  e |  p |  a |  r |  t |  y |
  
******* Cryptanalysis
- The only way is to brute force and try different key lengths.

******* Code

#+begin_src python :results output raw :wrap src :exports both
def encrypt(plaintext: str, rails: int):
    cleaned = plaintext.replace(" ", "")
    cipher = ""
    for i in range(rails):
        for j in range(i, len(cleaned), rails):
            cipher += cleaned[j]
    print(cipher)
    
encrypt("meet me after the party", 3)


def decrypt(ciphertext,key):
    n = len(ciphertext)
    plaintext = [''] * n
    idx = 0

    for i in range(key):
        for j in range(i, n, key):
            plaintext[j] = ciphertext[idx]
            idx += 1
    print(''.join(plaintext))
            
        

decrypt("mtaehayemfrereettpt", 3)
    
#+end_src

#+RESULTS:
#+begin_src
mtaehayemfrereettpt
meetmeaftertheparty
#+end_src

****** Columnar Transposition
- Write the characters of the message in rows over a specified number of
  columns.
- The number of columns is the length of the key, and the key tells us the order
  in which the cipher text is written.
- The cipher text is essentially the columns of this table written in the order
  the key was mentioned.
- For example, key = 4312567 (meaning 7 columns), and the plain text is "attack
  postponed until two am"

  | 4 | 3 | 1 | 2 | 5 | 6 | 7 |
  |---+---+---+---+---+---+---|
  | a | t | t | a | c | k | p |
  | o | s | t | p | o | n | e |
  | d | u | n | t | i | l | t |
  | w | o | a | m | x | y | z |

  The cipher text would be "ttnaaptmtsuoaodwcoixknlypetz".


**** Product

*** Based on Number of Keys

**** Single/Private Key or Symmetric Cryptography
- Here the same key is used for both encryption and decryption.
- Both the sender and the receiver shares this private key.

$$\text{Plain Text} \xrightarrow[\small{+key}]{\text{Encryption Algorithm (DES)}} \text{Transmitted Cipher Text}  \xrightarrow[\text{Decryption Algorithm}]{}  \text{Plain Text}$$

***** Feistel Cipher Structure
- There are $2^{n}$ ways of mapping for plain text
- Here, we use [[*Block][Block]] cipher
- For a plain text block of $n$ bits, the key length has to be $n \times 2^{n}$ bits.
- *Design Principles*:
  - Block size
  - Key size
  - Number of rounds
  - Subkey generation 

***** Data Encryption Standard (DES)
- This is the most widely used block cipher in the world.
- The key size is 64 reduced to 56 and the subkey size is 48 bits.
- The number of rounds and subkeys are 16.
- The cipher text is of 64 bits.
- Every round has substitution and transposition.
- Each round is defined as:
  $$L_{i} = R_{i-1}$$
  $$R_{i} = L_{i-1} \text{ xor } F(R_{0}, K_{1})$$
- Takes 32 bit R half and 48-bit subkey and:
  - Expands R to 48 bits using permutation E
  - Adds to subkey
  - Passes through 8 S-boxes to get 32 bit results
  - Finally permutes this using 32-bit permutation P.
    
file:/home/praaneshnair/gitProjects/org-notes/computer-security/One_round_of_DES.jpeg
    
****** S-Box
- Given a $4 \times 16$ box of 4 bit numbers, and a 6 bit number, you locate a number
  as:
  - The outer two bits (1st bit and 6th bit taken together) determines the row number
  - The inner bits (2nd, 3rd, 4th, 5th bit taken together) determines the column number
- The output is the binary number of the cell value.
- Note that this box is indexed from 0.

#+begin_src python :results output raw :wrap src :exports both
S1 = [
    [14, 4, 13, 1, 2, 15, 11, 8,
     3, 10, 6, 12, 5, 9, 0, 7],

    [0, 15, 7, 4, 14, 2, 13, 1,
     10, 6, 12, 11, 9, 5, 3, 8],

    [4, 1, 14, 8, 13, 6, 2, 11,
     15, 12, 9, 7, 3, 10, 5, 0],

    [15, 12, 8, 2, 4, 9, 1, 7,
     5, 11, 3, 14, 10, 0, 6, 13]
]

def sbox(S, bits):
    row = int(bits[0] + bits[5], 2)
    column = int(bits[1:5], 2)
    return f"{S[row][column]:04b}"
    
print(sbox(S1, "101010"))

#+end_src

#+RESULTS:
#+begin_src
0110
#+end_src

****** Decryption
- DES decryption is encryption in reverse order.
- The output of encryption generated from the 16th round with be the input to
  the first round.
| Double Decryption with 2 keys       | Triple Decryption with 3 keys                          | Triple Decryption with 2 keys                         |
|-------------------------------------+--------------------------------------------------------+-------------------------------------------------------|
| Encrypt using k1 \rightarrow Encrypt using k2 | Encrypt using k1 \rightarrow Encrypt using k2 \rightarrow Encrypt using k3 | Encrypt using k1 \rightarrow Decrypt using k2 \rightarrow Encrypt with k1 |
  




**** Two-key or Public Key cryptography or Asymmetric Cryptography
- It's called *asymmetric key encryption*.
- Public key is used to encrypt the message and private key is used to decrypt.
- Public key for Party b is denoted as $KU_{b}$
  $$C = E(\text{KB}_{B}, M)$$
- Private key for Party b is denoted as $KR_{b}$.
  $$M = D(\text{KU}_{B},E(\text{KR}_{B}, M))$$

***** Encryption/Decryption
- If you know the private key, you automatically get the public key too. But
  knowing the public key doesn't give you the public key at all.
- Not all algorithms support all the 3 applications. It may have one or two of
  the applications.
  
| Algorithm      | Encryption/Decryption | Digital Signature | Key Exchange |
|----------------+-----------------------+-------------------+--------------|
| RSA            | Yes                   | Yes               | Yes          |
| Elliptic Curve | Yes                   | Yes               | Yes          |
| Diffie-Hellman | No                    | No                | Yes          |
| DSS            | No                    | Yes               | No           |


***** Security of Public key algorithms
- Brute force is always possible, so make sure you:
  - Use a very large key
  - At the same time, consider the security/performance trade-off.
- Due to public/private key relationships, the number of bits in the key should
  be much larger the symmetric crypto keys.

***** RSA (Rivest Shamir Adelman) Algorithm
- This is the model widely used Public Key Cryptography (PKC).
- To encrypt a message there is no need to exchange a secret key separately.

****** Key Generation
- Select $p$, $q$, where $p$ and $q$ are prime.
- Calculate $n = p \times q$
- Select integer $e$, such that $\text{gcd}(\phi(n), e) = 1; 1 < e < \phi(n)$
- Calculate $d = e^{-1}\mod(\phi(n))$
- Public Key $\text{KU} = {e,n}$
- Private Key $\text{KR} = {d,n}$


****** Encryption
******* Rules
- Plaintext $M < n$
- Ciphertext $C = M^{d}\mod(n)$
******* Examples
******** Example 1
- $p=3$, $q=11$
- $n=p \times q = 3 \times 11 = 33$
- $\phi(n) = \phi(33) = \phi(3 \times 11) = 2 \times 10 = 20$
  - Verification of \phi(33): $Z_{33}^{*}$ = (all the numbers from 1 to 33, coprime with
    $33$) = [1,2,4,5,7,8,10,13,14,16,17,19,20,23,25,26,28,29,31,32]
- Consider $e=7$ (because it satisifies the GCD criteria):
- $d = e^{-1} \mod(20)$
  - $d = 7^{-1} \mod(20)$
  
 | $q$ | $a$ | $m$ | $r$ | $u_{0}$ | $u_{1}$ | $u$ |
 |-----+-----+-----+-----+------+------+-----|
 |   0 |   7 |  20 |   6 |    1 |    0 |   1 |
 
******** Example 2

****** Decryption
- Ciphertext = $C$
- Plaintext = $M = C^{d}\mod(n)$

****** Attacks against RSA

******* Brute Force


******* Mathematical Attakcs
- Factor n
- Calculate \phi(n)

******* Timings Attack
- Use the running time of the algorithm to determine the key

***** ElGamal Encryption Algorithm
- It's also a public-key cryptosystem like RSA.
- It's based on the difficulty of finding discrete logarithm. 

****** Algorithm
- Select a large prime $q$.
- Select $x$ to be a member of the group $Z_{q}^{*}$
- Select $g$ such that $y = g^{x} \mod(q)$
  - Public key: $(g,y,q)$
  - Private Key: $x$
  
****** Encryption
- Select a random number $r$ from $Z_{q}^{*}$
- $c_{1} = g^{r} \mod(q)$
  - $c_{1}$ carries the random exponent information required to compute the shared secret
  - $g$ is called the primitive root.
- $c_{2} = (p \cdot y^{r}) \mod(q)$
  - $c_{2}$ contains the encrypted message, and hence this is the only cipher text
    involved.

****** Decryption
- $P = [C_{2} (C_{1}^{x})^{-1}]\mod(q)$
- Encrypted message along with shared secret is needed for decryption.
- Use [[*Discrete Logarithm][Discrete Logarithm]]

  


****** Examples

******* Encrypt a message $m$ having value 10 using a public key $9$, where a random number generated is $3$ and primitive root $11$ and a prime number $23$
- Given:
  - $p=10$
  - $y=9$
  - $g=11$
  - $q=23$
  - $r=3$
- Encryption: 
  - $c_{1} = 11^{3} \mod(23) = 20$
  - $c_{2} = (10 \cdot 9^{3}) \mod(23) = 160 \mod(23) = 22$
  - Cipher text $C = (20, 22)$
- Decryption:
  - $20^{6} = 16\mod(23)$
  - Plaintext = $10$

******* $q = 23$, $g = 7$, $x = 9$, $r = 3$, $m = 20$
- 

***** Diffie Hellman 
- This is used for key-exchange where both the parties jointly establish a
  shared secret over an unsecured channel.
  
- Both parties agree on a generator $g$ (an integer) and a large prime number $p$, both of which are known to the public
- They possess their own private keys $a$ and $b$ respectively. Only they know
  about this.

  | Alice | Public   | Bob |
  |-------+----------+-----|
  | $a$   | $p$, $g$ | $b$ |
  
- Now calculate the public key:

  | Alice | Public                             | Bob |
  |-------+------------------------------------+-----|
  | $a$   | $p$, $g$                           | $b$ |
  |       | $A = g^{b} \mod(p)$, $B = g^{a} \mod(p)$ |     |

- Now we exchange public keys:
  
  | Alice            | Public                             | Bob              |
  |------------------+------------------------------------+------------------|
  | $a$              | $p$, $g$                           | $b$              |
  |                  | $A = g^{a} \mod(p)$, $B = g^{b} \mod(p)$ |                  |
  | $B = g^{b} \mod(p)$ |                                    | $A = g^{a} \mod(p)$ |

- Calculate shared secret key:
  
  | Alice                        | Public                             | Bob                          |
  |------------------------------+------------------------------------+------------------------------|
  | $a$                          | $p$, $g$                           | $b$                          |
  |                              | $A = g^{a} \mod(p)$, $B = g^{b} \mod(p)$ |                              |
  | $B = g^{b} \mod(p)$             |                                    | $A = g^{a} \mod(p)$             |
  | $\text{Secret Key} = K = B^{a}$ |                                    | $\text{Secret Key} = K = A^{b}$ |
  


****** Man in the Middle Attack

***** Digital Signature
- It's an authentication mechanism that enables the creator of a maessage to
  attach a code that acts as a signature.
- Digital signature is formed by taking the hash value of the message and
  encrypting the message with the sender's private key.
- After transmitting the message, both of us have the same message $m$ in
  plaintext. To verify that we actually have the same message, we verify the
  digital signature.
****** Properties of Digital Signature
- It must verify *author*, *date* and *time* of the signature.
- It must authenticate the *contents* at the time of signature.
- It must be *verifiable* by *third parties* to resolve disputes.

****** RSA Approach to Digital Signature
  | Sender                                                                                                                                       | Receiver                                                                                                                                                                                                                             |
  |----------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
  | The hash of message $m$ is computed as $h$, and then you encrypt this hash using the sender's private key to get the message's signature $S$ | The receiver also computes the hash $h$ of the message $m$. Next, the signature $S$ that the sender provided, is decrypted using the receiver's public key. If the decrypted value is the same as $h$, then the message is verified. |
  
****** DSS (Digital Signature Standard)
- Digital signatures are generated using *Secure Hash Algorithm* (SHA). 
- Here, instead of a key, we use a *digital signature function*.

******* Sender Side/ Signing
- A hash value is generated from the message.
- There are 4 inputs given to the signature generation function:
  - The hash value
  - A random number $k$
  - The sender's private key $PR(a)$
  - The global public key $PU(g)$
- The signature function generates two components $s$ and $r$, where $r \neq 0$.
- ($m$, $s$, $r$) are sent to the receiver.

******* Receiver Side
- The hash value is generated from the message.
- The signature verification function takes 5 inputs:
  - The hash value
  - $s$ and $r$
  - Public key of sender $PU(a)$
  - The global public key $PU(g)$
- The output of the verification function is compared with $r$.
- If they match, the signature is valid.

****** DSA (Digital Signature Algorithm)
- The values used here are:
  - $p$: 512 - 1024 bit prime number
  - $q$: 160 bit prime number, such that $q \mid p-1$
  - $x$: Any integer such that $0 < x < q$
  - $y = g^{x} \mod(p)$

******* Sender Side/ Signing
- Pick a random number $k$ such that $0 < k < q$
- $r = (g^{k}\mod(p)) \mod(q)$
- $s = k^{-1}(\text{SHA1}(m) + x\cdot r) \mod(q)$
- ($m$, $s$, $r$) are sent to the receiver.

******* Verification
- $w = s^{-1}\mod(q)$
- $u1 = (\text{SHA1}(m) \times w)\mod(q)$
- $u2 = (r \times w) mod q$ 
- $v = (g^{u1} \times y^{u2} \mod(p)) \mod(q)$
- If $v$ and $r$ give the same number, the signature is verified.


***** Hash Function
- A hash is a unique digital fingerprint of data. It's a mathematical blender.
- A hash function will always return *fixed length* output, regardless of the input size.
- It is *deterministic* (the same input always produces the same hash)
- Even a tiny change in input produces a completely different hash. This is
  called the *avalanche effect*.
- Hashes are *puzzle-friendly* because the avalanche effect makes sure there are
  no shortcuts.
- Two inputs can never give the same hash. 
- Hashes provide:
  - *Authentication*: Verifies identity of sender
  - *Integrity*: Ensures data wasn't tampered
  - *Non-Repudiation*: Makes sure that the sender can't deny sending it
    
****** Properties
  
  | Property                  | Description                                                                                             |
  |---------------------------+---------------------------------------------------------------------------------------------------------|
  | Variable Input Size       |                                                                                                         |
  | Fixed Output Size         |                                                                                                         |
  | Preimage Resistant        | It's a one-way property, as given the hash it's computationally infeasible to find the original message |
  | Second preimage resistant | Given $H(x)$, $H(y)$ and $y$, if you know $H(x) = H(y)$, it doesn't mean $x = y$ (you can't find $x$)   |
  | Collision Resistant       | It's computationally infeasible to find ($x$,$y$) if $H(x) = H(y)$                                      |


******* SHA-256
- SHA-256 works on 512-bit blocks.
- The last 64 bits are reserved for storing the length of the original message.
- The message itself is stored in the rest of the 448 bits.

******** Algorithm
1. Read the input
2. Convert it into binary
3. Append a bit with value 1, to the end of this sequence.
4. Pad this sequence with enough 0s to span across 448 bits.
5. Pad the length of the original message with enough 0s to span across 64 bits.
6. Define the *working variables*:
   #+begin_src txt
H0 = 6a09e667
H1 = bb67ae85
H2 = 3c6ef372
H3 = a54ff53a
H4 = 510e527f
H5 = 9b05688c
H6 = 1f83d9ab
H7 = 5be0cd19
   #+end_src
   Initialize variables ~a~, ~b~, ~c~, ~d~, ~e~, ~f~, ~g~, ~h~ with ~H0~, ~H1~, ~H2~, ~H3~, ~H4~, ~H5~, ~H6~,
   ~H7~ respectively.
7. Define the *round constants*:
   - These are 64 words each of size 32 bits.   
   - These are derived from the decimal part (eg. 2 from the number 1.2) of the
     cube roots of the first 64 prime numbers.
      #+begin_src txt
   K0 = 0x428a2f98
   K1 = 0x71374491
   K2 = 0xb5c0fbcf
   K3 = 0xe9b5dba50x3956c25b
   K4 = 0x59f111f1
   K5 = 0x923f82a4
   K6 = 0xab1c5ed50xd807aa98
   K7 = 0x12835b01
   ...
   K63 = 0xc67178f2
      #+end_src
8. Split the block of 512 bits into 16 unsigned words w0, w1, w2, .. w15 (each
   would be 32 bits).
9. Expand these 16 words into 64 words (create w16, w17, ... w63) using
   rotations, shifts and XOR. Each word is created as:
   \[W_i = \sigma_1(W_{i-2}) + W_{i-7} + \sigma_0(W_{i-15}) + W_{i-16} \]
   for $16 \le i \le 63$
   - The current word $w_{i}$ depends on 4 different previous words ($w_{i-2}$,
     $w_{i-7}$, $w_{i-15}$ and $w_{i-16}$).
   - The helper functions defined are:
     - $\operatorname{ROTR}^{n}(x)$: Rotate right (right circular shift) all the bits of
       word $x$, $n$ times.
     - $\operatorname{SHR}^{n}(x)$: Logical right shift (bits of the right are discarded on
       right shifting) all the bits of word $x$, $n$ times.
     - $\sigma_{0}(x) = \operatorname{ROTR}^{7}(x) \oplus \operatorname{ROTR}^{18}(x) \oplus \operatorname{SHR}^{3}(x)$
     - $\sigma_{1}(x) = \operatorname{ROTR}^{17}(x) \oplus \operatorname{ROTR}^{19}(x) \oplus \operatorname{SHR}^{10}(x)$
10. For 64 times:
    1. Calculate:
       \[T_1 = h + \Sigma_1(e) + \operatorname{Ch}(e,f,g) + K[i] + W[i] \]
       \[T_2 = \Sigma_0(a) + \operatorname{Maj}(a,b,c) \]
       The helper functions/variables are defined as:
       - $h$: This variable is one of the 8 variables defined earlier
       - $\Sigma_{0}(x) = \operatorname{ROTR}^{2} \oplus \operatorname{ROTR}^{13} \oplus \operatorname{ROTR}^{22}$
       - $\Sigma_{1}(x) = \operatorname{ROTR}^{6} \oplus \operatorname{ROTR}^{11} \oplus \operatorname{ROTR}^{25}$
       - $\operatorname{Ch}(e, f, g) = (e \wedge f) \oplus (\not e \vee g)$ \\
         - This is called the *Choice function* and $e$, $f$ and $g$ are 3 of the 8
           working variables.
         - For every bit position, if the bit of $c$ is 0, then the corresponding
           bit is taken from $f$ and if the bit of $c$ is 1, then the
           corresponding bit is taken from $g$.
       - $\operatorname{Maj}(a, b, c) = (a \wedge b) \oplus (a \wedge c) \oplus (b \wedge c)$
         - This is the *Majority function* and for each bit position, the output
           is the bit value (0 or 1) that appears in at least two of the three
           inputs.
    2. Update the worker variables as:
       - $\verb|H7| = \verb|H6|$
       - $\verb|H6| = \verb|H5|$
       - $\verb|H5| = \verb|H4|$
       - $\verb|H4| = (\verb|H3| + T_{1}) \mod(2^{32})$
       - $\verb|H3| = \verb|H2|$
       - $\verb|H2| = \verb|H1|$
       - $\verb|H1| = \verb|H0|$
       - $\verb|H0| = (T_{1} + T_{2}) \mod(2^{32})$
11. Concatenate all the worker variables and convert the result into hexadecimal.
     
   
******** Rough Implementation in Python
#+begin_src python :results output raw :wrap src :exports both :tangle sha256.py
def main():
    message = "quickbrown"
    output = convert_string_to_binary(message)
    output+='1'
    output = pad_till_n(output, 448)
    output+= f"{len(message):0{64}b}"
    
    # working variables:
    H = [
        f"{int(x,16):032b}" for x in
        [
             "6a09e667",
             "bb67ae85",
             "3c6ef372",
             "a54ff53a",
             "510e527f",
             "9b05688c",
             "1f83d9ab",
             "5be0cd19",
         ]
    ]
    # round constants
    K = [
         0x428A2F98, 0x71374491, 0xB5C0FBCF, 0xE9B5DBA5,
         0x3956C25B, 0x59F111F1, 0x923F82A4, 0xAB1C5ED5,
         0xD807AA98, 0x12835B01, 0x243185BE, 0x550C7DC3,
         0x72BE5D74, 0x80DEB1FE, 0x9BDC06A7, 0xC19BF174,
         0xE49B69C1, 0xEFBE4786, 0x0FC19DC6, 0x240CA1CC,
         0x2DE92C6F, 0x4A7484AA, 0x5CB0A9DC, 0x76F988DA,
         0x983E5152, 0xA831C66D, 0xB00327C8, 0xBF597FC7,
         0xC6E00BF3, 0xD5A79147, 0x06CA6351, 0x14292967,
         0x27B70A85, 0x2E1B2138, 0x4D2C6DFC, 0x53380D13,
         0x650A7354, 0x766A0ABB, 0x81C2C92E, 0x92722C85,
         0xA2BFE8A1, 0xA81A664B, 0xC24B8B70, 0xC76C51A3,
         0xD192E819, 0xD6990624, 0xF40E3585, 0x106AA070,
         0x19A4C116, 0x1E376C08, 0x2748774C, 0x34B0BCB5,
         0x391C0CB3, 0x4ED8AA4A, 0x5B9CCA4F, 0x682E6FF3,
         0x748F82EE, 0x78A5636F, 0x84C87814, 0x8CC70208,
         0x90BEFFFA, 0xA4506CEB, 0xBEF9A3F7, 0xC67178F2
    ]
    # split the block into 16 words (w0, w1, ... w15) of 32 bits each
    w = []
    for i in range(0, 512, 32):
        w.append(output[i:i+32])

    # creating words w16, w17, ... w63 (helper functions defined later)
    for i in range(16, 64):
        value = (sigma_1(w[i-2]) + int(w[i-7], 2) + sigma_0(w[i-15]) + int(w[i-16], 2)) % (2**32)
        w.append(f"{value:032b}")

    # the 64 rounds (helper functions defined later)
    for i in range(64):
        T1 = (int(H[7], 2) + SIGMA_1(H[4]) + Ch(H[4], H[5], H[6]) + K[i] + int(w[i], 2)) % (2**32)
        T2 = (SIGMA_0(H[0]) + Maj(H[0], H[1], H[2])) % (2**32)
        H[7] = H[6]
        H[6] = H[5]
        H[5] = H[4]
        H[4] = f"{(int(H[3],2) + T1) % (2**32):032b}"
        H[3] = H[2]
        H[2] = H[1]
        H[1] = H[0]
        H[0] = f"{(T1 + T2) % (2**32):032b}"

    print(hex(int("".join(H), 2)))




def convert_string_to_binary(txt: str):
    binary = ""
    for c in txt:
        binary += f"{ord(c)-96:08b}"
    return binary

def pad_till_n(txt: str, n):
    return txt.rjust(n, "0")


# helper functions for creating words w16, w17, ... w63
def ROTR(w, n): 
    n = n%len(w)
    return w[-n:] + w[:-n]

def SHR(w, n):
    return w[:-n].rjust(len(w), "0")

def sigma_0(x):
    return int(ROTR(x, 7), 2) ^ int(ROTR(x, 18), 2) ^ int(SHR(x, 3), 2)

def sigma_1(x):
    return int(ROTR(x, 17), 2) ^ int(ROTR(x, 19), 2) ^ int(SHR(x, 10), 2)
        



# helper functions for the 64 rounds
def SIGMA_0(x):
    return int(ROTR(x, 2), 2) ^ int(ROTR(x, 13), 2) ^ int(ROTR(x, 22), 2)
    
def SIGMA_1(x):
    return int(ROTR(x, 6), 2) ^ int(ROTR(x, 11), 2) ^ int(ROTR(x, 25), 2)

def Ch(e, f, g):
    return (int(e, 2) & int(f, 2)) ^ (~int(e, 2) & int(g, 2))
    
def Maj(a, b, c):
    return (int(a, 2) & int(b, 2)) ^ (int(a, 2) & int(c, 2)) ^ (int(b, 2) & int(c, 2))

main()

#+end_src

#+RESULTS:
#+begin_src
0xc072e1042417d4a9c774c9ffeaea3d25440a6479978c2adc1cacdc9a894c35bc
#+end_src


******** Using ~hashlib~
The steps in which this works is given below:
********* Make ~bytes~ Object
- A ~bytes~ object in Python is an immutable sequence of integers ranging from 0
  to 255.
- You can make it using by passing a list of integers as the parameter to the
  ~bytes~ function:
  #+begin_src python :results output raw :wrap src :exports both
list_bytes = bytes([72, 101, 108, 108, 111])
print(list_bytes)
  #+end_src

  #+RESULTS:
  #+begin_src
  b'Hello'
  #+end_src
- You can also use a ~b~ suffix to a string:
  #+begin_src python :results output raw :wrap src :exports both
list_bytes = b'hello'
print(list_bytes)
  #+end_src

  #+RESULTS:
  #+begin_src
  b'hello'
  #+end_src
- You can also use the ~.encode()~ method and it gives the same thing:
  #+begin_src python :results output raw :wrap src :exports both
list_bytes = 'hello'.encode()
print(list_bytes)
  #+end_src

  #+RESULTS:
  #+begin_src
  b'hello'
  #+end_src
- If you index a ~bytes~ object, you get the ASCII value:
  #+begin_src python :results output raw :wrap src :exports both
print(b'ABC'[0])
  #+end_src

  #+RESULTS:
  #+begin_src
  65
  #+end_src

  
********* Use ~.sha256()~ method
- From the ~hashlib~ module, the ~.sha256()~ method takes a ~bytes~ object as a
  parameter, and returns a ~HASH~ object:
  #+begin_src python :results output raw :wrap src :exports both
import hashlib
print(type(hashlib.sha256(b'ABC')))
  #+end_src

  #+RESULTS:
  #+begin_src
  <class '_hashlib.HASH'>
  #+end_src

********* Use ~.hexdigest()~ method
- On the ~HASH~ object, you can call the ~.hexdigest()~ method to return the hashed
  value as hexadecimal characters:
  #+begin_src python :results output raw :wrap src :exports both
import hashlib
hash_value = hashlib.sha256("text".encode()).hexdigest()
print(hash_value)
  #+end_src

  #+RESULTS:
  #+begin_src
  982d9e3eb996f559e633f4d194def3761d909f5a3b647d1a851fead67c32c9d1
  #+end_src


******* HMAC
This is assuming the hash function where each character’s ASCII value is
multiplied by a large prime number, added to the running hash value, and reduced
using modulo arithmetic. The resulting number acts as the hash of the message.
#+begin_src python :results output raw :wrap src :exports both
def simple_hash(message):
    prime = 1000003
    mod = 1000000007

    result = 0

    for ch in message:
        result = (result + ord(ch) * prime) % mod

    return result


def hmac_simple(key, message):
    ipad = 0x36
    opad = 0x5C

    inner_key = ""

    for ch in key:
        inner_key += chr(ord(ch) ^ ipad)

    inner = simple_hash(inner_key + message)

    outer_key = ""

    for ch in key:
        outer_key += chr(ord(ch) ^ opad)

    result = simple_hash(outer_key + str(inner))

    return result


print(hmac_simple("SECRET", "AUTHENTICATE"))

#+end_src

#+RESULTS:
#+begin_src
577001731
#+end_src

*** Based on how plaintext is processed

**** Block
- Block Cipher transforms a fixed length of plaintext data into a block of
  ciphertext of the same length, with the help of a secret key.
- The most commonly used length of text (size of the block) is 64 bits.
- Two types are:
  - Transposition
  - Substitution
- Block cipher models are used for *symmetric cipher models*.
- In Block ciphers, the input and output have to be of the same length.
- There are two types of mapping: 
  - Reversible: The cipher text is unique for every plain text. 
  - Irreversible
- The ideal block cipher is equivalent to a classical substitution cipher, which is prone to attacks.
- To overcome this, an *arbitrary reversible substitution cipher* can be used,
  where the statistical characteristics of the plain text is masked.
- Using a large block size increases security but is impractical to implement.
- For example, in [[*Feistel Cipher Structure][Feistel Cipher Structure]] a plain text block of $n$ bits, the
  key length has to be $n \times 2^{n}$ bits.
- The ideal block cipher uses the concept of *product cipher* where product cipher
  is a combination of substitution and permutation. [[*Feistel Cipher Structure][Feistel Cipher Structure]]
  proposed this concept.
- Most ciphers are based on [[*Feistel Cipher Structure][Feistel Cipher Structure]].

***** Confusion and Diffusion
| Confusion                                                                        | Diffusion                                                                                                                          |
|----------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------|
| Makes the relationship between cipher text and plain text as complex as possible | It hides the statistical structure of the plaintext by repeatedly applying permutations, and then applying the encryption function |


**** Stream
- The encryption is done bit by bit
- The principle applied is only confusion (no diffusion).
- Block ciphers like vernam needs such a big key to be stored and sent safely.
  Instead, you have a smaller key that generates a larger keystream.
- A simple stream cipher is where you keep repeating the smaller key till it
  matches the input size.

* Number Theory

** Basic Properties

*** Commutative
$$a + b = b + a$$
*** Associative
$$a + (b+c) = (a+b)+c$$
Same applies to multiplication too.

*** Distributive
$$a \times (b+c) = ab + ac$$
** Division
- When we say $a | b$ (a divides b), we're doing $\frac{b}{a}$.
- $b$ is the dividend and $a$ is the divisor.
  $$divident = quotient \times divisor + remainder$$ 
  - Divident is the number that is getting split up.
  - Divisor is the number that does the dividing/splitting.
- $\text{Divisor}|\text{Divident}$ literally reads "the divisor perfectly
  divides the divident" and this implies that the remainder of this division
  process is 0. (Obvious facts, but I still chose to put them here).

** Prime Numbers
- A prime number is a natural number greater than 1 that has no positive
  divisors other than 1 and itself.
- Euclid states that there are infinitely many prime numbers.

*** Twin Primes
- Pairs of primes which differ by 2.
- Eg. 3 and 5

*** Primality Test
**** What it is
- To test if a number $n$ is prime, you check if it's divisible with any prime
  number from 2 to $\sqrt{n}$.
- For example, checking 97:
  - $\sqrt{97} \approx 9$
  - We check if 97 is divisible by 2, 3, 5, 7.
  - Since it's not, we can conclude that 97 is a prime number.
- You can use this test for numbers as big as those with magnitude of $10^{12}$.
  This is the safe upperbound widely taught in computer science, as beyond this
  finding square root takes time.
  
**** Code for Trial Division Method
#+begin_src python :results output raw :wrap src :exports both
from math import sqrt

def main():
    print(is_prime(97))

def is_prime(n):
    if n%2==0:
        return False
    for i in range(3, 1+int(sqrt(n)), 2):
        if n%i == 0:
            return False
    return True
    
main()

#+end_src

#+RESULTS:
#+begin_src
True
#+end_src

*** Fundamental Theorem of Arithmetic
#+begin_quote
Every positive integer is uniquely a product of prime numbers.
#+end_quote

*** Sieve of Eratosthenes

- This is one of the fastest ways to find *all prime numbers up to a given number N*.

- The key idea is:
  - If a number =p= is prime, then *all multiples of p greater than p are composite*.
  - Therefore, we can find primes by repeatedly *eliminating the multiples of known primes*.
  - This process is called the *Sieve of Eratosthenes*.

**** Algorithm

Initially, write down all numbers from 2 to N:

#+begin_src txt
2  3  4  5  6  7  8  9  10
11 12 13 14 15 16 17 18 19 20
21 22 23 24 25 26 27 28 29 30
#+end_src

1. Start with the first number, =2=.
2. Since 2 has not been crossed out, it is *prime*.
3. Cross out all multiples of 2, because they are composite:
   #+begin_src txt
2  3  X  5  X  7  X  9  X
11 X  13 X  15 X  17 X  19 X
21 X  23 X  25 X  27 X  29 X
   #+end_src

4. Move to the next number that has not been crossed out: =3=.
5. 3 is prime, so cross out all of its multiples:
   #+begin_src txt
2  3  X  5  X  7  X  X  X
11 X  13 X  14 X  17 X  19 X
X  22 23 24 25 X  X  28 29 X
   #+end_src

6. Continue this process for the next uncrossed number. You only need to perform
   the crossing-out process for prime numbers up to $\sqrt{N}$.

7. In the actual process, we start crossing multiples from $p^{2}$. When processing
   a prime number =p=, you start crossing out from $p^{2}$ rather than from $2p$. For
   example, when p=5, its multiples are:
   \[10,\ 15,\ 20,\ 25,\ 30,\ldots \]
   
   But 10, 15, and 20 have *already been crossed out* when we processed 2 and 3.
   The first multiple that could still be uncrossed is $5^{2} = 25$. In general, we cross out:
   \[p^2,\ p(p+1),\ p(p+2),\ldots \]



*** GCD
**** What it is
- Greatest common divisor is the largest number that divides both numbers.
- Consider this example:
  $$8  = 2 \times 2 \times 2$$
  $$32 = 2 \times 2 \times 2 \times 2 \times 2$$
- GCD tells us how many 2's you can take such that both numbers definitely have.
  The limiting factor is the smaller number (8) and hence:
  #+begin_quote
When you have two numbers:
$$\text{num1} = x^{a} \times y^{b} \times z^{c}$$
$$\text{num2} = x^{p} \times y^{q} \times z^{r}$$
- The GCD of $\text{num1}$ and $\text{num2}$ is $\text{min}(a,p) \times \text{min}(b,q) \times \text{min}(c,r) \times \text{. . .}$
  #+end_quote
- For LCM, it would be $\text{max}(a,p) \times \text{max}(b,q) \times \text{max}(c,r) \times
  \text{. . .}$, because you need the smallest number that the numbers themselves can completely fit themselves in. 
- Consider a Venn diagram, where each circle is $\text{num1}$ and $\text{num2}$.
  The contents inside a circle are all the primes that number contains. For
  example the contents of the number 24 would be 2, 2, 2 and 3, since $24 = 2^{3} \times
  3$
  - GCD is the intersection of primes and it's the common part in the venn
    diagram. Hence you take the minimum of the powers.
  - LCM is the union of primes and it's both the numbers taken together as a
    whole.
  

**** How to find
For example, the GCD for 24598 and 7895 would be:

*Prime factorization of 24798*
| /2/   | 24598 |
| /7/   | 12299 |
| /7/   |  1757 |
| /251/ |   251 |
| 1   |     1 |

*Prime factorization of 7895*
| /5/    | 7895 |
| /1579/ | 1579 |
| 1    |    1 |

The answer is *1*.

*** Euclidean Algorithm
**** What it is
Basically, the property used is that $GCD(a,b) = GCD(a\mod(b), b)$, given that
$a>b$. You can endlessly keep replacing the larger of the two numbers, with the
remainder they form on dividing. You keep doing this until the remainder is 0
(the value of the smaller number is the GCD).

For example, the GCD of 49 and 63 would be 7:

| q |  a |  b | $r = a\mod(b)$ |
|---+----+----+----------------|
| 1 | 63 | 49 |             14 |
| 3 | 49 | 14 |              7 |
| 2 | 14 |  7 |              0 |

What we've done here is $GCD(63,49) = GCD(49, 14) = GCD(14, 7) = GCD(7, 0) = 7$
(because GCD of a number and 0, is the number itself).

**** Code
#+begin_src python :results output raw :wrap src :exports both
def main():
    print(gcd(63,49))

def gcd(a, b):
    if b==0:
        return a
    else:
        return gcd(b, a%b)

main()

#+end_src

#+RESULTS:
#+begin_src
7
#+end_src

*** Modular Arithmetic Operations
- *Modular arithmetic* is the arithmetic performed on remainders after division by
  a fixed positive integer.
- So in $a\mod(n)$, $n$ must be positive.
  
**** Standard Rules
$$[a\mod(n) + (b\mod(n))]\mod(n) = (a+b)\mod(n)$$
$$[a\mod(n) - (b\mod(n))]\mod(n) = (a-b)\mod(n)$$
$$[a\mod(n) \times (b\mod(n))]\mod(n) = (a \times b)\mod(n)$$

In the above example, if $b = a$, then you'd have
$$[a\mod(n) \times (a\mod(n))]\mod(n) = a^{2} \mod(n)$$
So to generalize it:
$$[(a\mod(n))^{b}]\mod(n) = a^{b} \mod(n)$$





*Note*: The notation of modulo $m$ is $Z_{m}$

**** Inferences
Some inferences you can make out from this is:
- $(a-b)\mod(n) = 0$ is the same as $a\mod(n) = b\mod(n)$.

**** How to do $(\text{negativeNumber})\mod(x)$
- It's simply $(\text{negativeNumber}+nx)\mod(x)$, where $n$ can be anything
  that turns that negative number into a positive one.


**** Program to compute $(a+b)mod(n)$ and $(a*b)mod(n)$
#+begin_src python :results output raw :wrap src :exports both
def main():
    print(a_plus_b_mod_n(15, 37, 13))
    print(a_plus_b_mod_n(15, 37, 13))

def a_plus_b_mod_n(a, b, n):
    return (a%n + b%n)%n

def a_times_b_mod_n(a, b, n):
    return (a%n * b%n)%n

main()

#+end_src

#+RESULTS:
#+begin_src
0
0
#+end_src

*** Addition Modulo $n$ table
- We construct a table where each value is $(row + col) \mod (n)$
- For example, let $n=7$:

  | $(row + col)\mod(7)$ | *0* | *1* | *2* | *3* | *4* | *5* | *6* |
  | *0*                    | 0 | 1 | 2 | 3 | 4 | 5 | 6 |
  | *1*                    | 1 | 2 | 3 | 4 | 5 | 6 | 0 |
  | *2*                    | 2 | 3 | 4 | 5 | 6 | 0 | 1 |
  | *3*                    | 3 | 4 | 5 | 6 | 0 | 1 | 2 |
  | *4*                    | 4 | 5 | 6 | 0 | 1 | 2 | 3 |
  | *5*                    | 5 | 6 | 0 | 1 | 2 | 3 | 4 |
  | *6*                    | 6 | 0 | 1 | 2 | 3 | 4 | 5 |

*** Congruence
$$a \equiv b \mod(n)$$
- This means that $a\mod(n) = b\mod(n)$.
- When you do $a \div n$ and $b \div n$, you get the same remainder.
- One way of saying this is that $a$ and $b$ differ by a multiple of $n$.


*** Inverses
**** Additive Inverse
$$-a + a\mod(m) = 0$$

**** Multiplicative Inverse
- Normal multiplicative inverse of $a$ is a number such that if you multiply $a$
  with it, you get 1. $$a \times x = 1$$ and the value of $x = a^{-1}$.

- In modulo arithmetic:
  $$a \times x \equiv 1 \mod(m) $$
  

- The multiplicative inverse of $a\mod(m)$ is $x$ such that $a\cdot x\mod(m) = 1\mod(m) = 1$.
*Note*:
- Multiplicative inverse of $a \mod(n)$ is represented as $a^{-1} \mod(n)$
- Multiplicative inverse exists for $a \mod(n)$ if $GCD(a,n) = 1$.
- For example, $2^{-1} \mod(7) = 4$, i.e. $2 \times 4 \mod(7) = 1$
  - Hence 4 is the multiplicative inverse of $2\mod(7)$.
  - Also, 2 is the multiplicative inverse of $4\mod(7)$.
- All in all, to find $a^{-1}\mod(m)$, find the number $x$ to multiply $a$ with,
  such that $a \times x \mod(m) = 1$.

***** Extended Euclidean Algorithm
****** What it is
- Consider this example of finding multiplicative inverse of $356\mod(45)$ or
  $356$ in $Z_{45}$ (different ways of asking the same thing):

  $$u = u_{0} - q \cdot u_{1}$$ And in the below table, always initialize $u_{0}$ and $u_{1}$
  to be 1 and 0 respectively.

 | $q$ | $a$ | $m$ | $r$ | $u_{0}$ | $u_{1}$ | $u$ |
 |-----+-----+-----+-----+------+------+-----|
 |   7 | 356 |  45 |  41 |    1 |    0 |   1 |
 |   1 |  45 |  41 |   4 |    0 |    1 |  -1 |
 |  10 |  41 |   4 |   1 |    1 |   -1 |  11 |
 |   4 |   4 |   1 |   0 |   -1 |   ~11~ |     |

 The value of $u_{1}$ in the row where $r$ becomes 0, is the multiplicative inverse.

- In the above table, you always carry the value of $a$ , $m$ , $u_{0}$ and $u_{1}$
  from their respective top right neighbour, but you calculate $q$ and $r$.

- Check if $2^{-1}\mod(10)$ exists:
  - Can't be found because $GCD(2, 10) = 2 \ne 1$
  - Hence multiplicative inverse doesn't exist
    
- Find the multiplicative inverse of $9\mod(10)$:
  
 | $q$ | $a$ | $m$ | $r$ | $u_{0}$ | $u_{1}$ | $u$ |
 |-----+-----+-----+-----+------+------+-----|
 |   0 |   9 |  10 |   9 |    1 |    0 |   1 |
 |   1 |  10 |   9 |   1 |    0 |    1 |  -1 |
 |   9 |   9 |   1 |   0 |    1 |   ~-1~ |     |

 The multiplicative inverse is -1. So it's $-1\mod(10) = (-1+10)\mod(10) = 9$
 So the final multiplicative inverse is 9.
 
****** Code
#+begin_src python :results output raw :wrap src :exports both
def main():
    print(extended_euclidean(9, 10))


def extended_euclidean(a, m):
    return rec(a, m, 1, 0)


def rec(a, m, u0, u1):
    if m == 0:
        return u0
    else:
        q = a // m
        return rec(m, a % m, u1, u0 - q * u1)


main()
#+end_src

#+RESULTS:
#+begin_src
-1
#+end_src

***** Multiplicative Inverse Pair

- In general, if we have $a \cdot x \mod(m) = 1$, then $(a,x)$ is a multiplicative inverse pair.
- When we're asked to find *multiplicative inverse pair* of, say $Z_{10}$, we have to
  find the pairs of numbers which are multiplicative inverses of each other.

  | $1\cdot x \mod(10)$ | $x=1$ |
  | $2\cdot x \mod(10)$ | $x=1$ |

 
***** Solving a congruence
- Consider the example $$15x \equiv 7\mod(32)$$
- Since ~GCD(15,32) = 1~, we can find the modular inverse of $15\mod(32)$.
  - $15a \equiv 1\mod(32)$
  - $a = 15$
  - Hence $15 \equiv 15^{-1}\mod(32)$
- $15x \equiv 7\mod(32)$
- Multiply both sides by the value of $15^{-1}\mod(32)$
- $15 \times 15x \equiv 15 \times 7\mod(32)$
- $x \equiv 105\mod(32)$ because $15 \times 15 \equiv 1\mod(32)$
- $x \equiv 9\mod(32)$
 


*** Equivalence Class
- A Equivalence/residual class is a set of integers that are equivalent to each
  others modulo $n$.

  $a \equiv b\mod(n)$

- For example: $12 \equiv 18\mod(15)$
  - $12\mod(15) = 12$ and $18\mod(15) = 3$
  - Since $3 \neq 15$, $12 \equiv 18\mod(15)$ is not a valid Equivalence class.
    
- Another example: $4 \equiv -18\mod(11)$
  - $4\mod(11) = 4$ and $-18\mod(11) = 4$
  - Since $4 = 4$, $4 \equiv -18\mod(11)$ is a valid Equivalence class.
    
- Another example: $4^{-1} \equiv 2\mod(7)$ (this is not multiplicative inverse)
  - $\frac{1}{4} = 2\mod(7)$
  - $\frac{1}{4} \times 4 = (2 \times 4)\mod(7)$
  - $1 = 8\mod(7)$
  - This becomes your new Equivalence class.

  
** Euler's Totient/Phi Function
- $Z_{m}^{*}$ is the set of numbers, that are relatively prime or coprime with $m$ in
  $Z_{m}$. 
- $Z_{m}$ is the set of numbers from $0$ to $m-1$.
- For example, $m=14$
  - $Z_{m}$ = {0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13}
  - $Z_{m}^{*}$ = {0, 1, 3, 5, 7, 9, 11, 13}
- *Euler's Totient function* is denoted by $\phi(n)$, and it is the number of
  elements in $Z_{m}^{*}$.
  $$\phi(n) = |Z_{m}^{*}|$$

*** Conditions for $\phi(P)$
1. $\phi(p) = p-1$, if $p$ is a prime number.
2. $\phi(p) = \phi(m \times n) = \phi(m) \times \phi(n)$, if $m$ and $n$ are coprime.
3. $\phi(m) = \phi(p^{e}) = p^{e} - p^{e-1}$, if $p$ is prime.

*** Examples

**** $\phi(27)$
- $\phi(3^{3}) = 3^{3} - 3^{2} = 18$

**** $\phi(630)$
- $\phi(630) = \phi(63 \times 10)$
- $\phi(630) = \phi(63) \times \phi(10) = (63 - 7) \times (\phi(2)\times\phi(5))$
- $\phi(630) = 56 \times 1$
- $\phi(630) = 56$
  
** Fast Exponentiation Algorithm
#+begin_quote
Squaring and selective multiplication method.
#+end_quote

*** Steps
**** Convert the number $B$ into binary. Represent $B$ as a sum of unique powers of 2.
Eg. $B = 11$
- $B$ in binary is ~1011~.
- So $B = 8 + 2 + 1$

**** $A^{i}\mod(C)$ such that $i \le B$


**** Find $A^{C}\mod(C)$,

*** Examples

**** $11^{13}\mod(53)$
- Step 1:
  - $13 = 8 + 4 + 1$
- Step 2: 
  - $11^{1}\mod(53) = 11\mod(53) = 11$
  - $11^{2}\mod(53) = (11^{1}\mod(53) \times 11^{1}\mod(53))\mod(53) = 121\mod(53) = 15$
  - $11^{4}\mod(53) = (11^{2}\mod(53) \times 11^{2}\mod(53))\mod(53) = 225\mod(53) = 13$
  - $11^{8}\mod(53) = (11^{4}\mod(53) \times 11^{4}\mod(53))\mod(53) = 169\mod(53) = 10$
- Step 3:
  - $11^{(8 + 4 + 1)}\mod(53) = (11^{8}\mod(53) \times 11^{4}\mod(53) \times 11^{1}\mod(53))\mod(53)$
  - $11^{(13)}\mod(53) = (10 \times 13 \times 11)\mod(53)$
  - $11^{(13)}\mod(53) = (1430)\mod(53)$
  - $11^{(13)}\mod(53) = 52$
- Hence $11^{(13)}\mod(53) = 52$

  

*** Code
#+begin_src python :results output raw :wrap src :exports both
def main():
    fast(11, 13, 53)

def fast(a, b, n):
    modval = (a**1) % n
    power = 1
    dp = []
    
    while power <= b:
        dp.append((power, modval))

        power*=2
        modval = (modval**2) % n
    print(dp)

    
    result = 1
    for powr, val in dp:
       if b & powr:
          result = (result * val) % n

    print(result) 

main()

#+end_src

#+RESULTS:
#+begin_src
[(1, 11), (2, 15), (4, 13), (8, 10)]
52
#+end_src

** Fermat's Little Theorem
#+begin_quote
$a^{p-1} \equiv 1\mod(p)$, if
- $a$ is an integer, $p$ is a prime number
- $p \nmid a$ ($p$ doesn't divide $a$)
#+end_quote
You can check if a number is prime by putting its value as $p$. If it doesn't
satisfy fermat's theorm, it's composite.

For example, verifying Fermat's little theorem for $p = 31$ and $a = 3$.
- $3^{(31-1)}\mod(31)$

*** Examples
**** Find $3^{-1}\mod(31)$ using Fermat's Little Theorem
- By Fermat's little theorem, $3^{30} \equiv 1\mod(31)$
- On dividing by 3, you get  $3^{29} \equiv \frac{1}{3}\mod(31)$
- $3^{29} \equiv 3^{-1}\mod(31)$
- $3^{-1} \equiv 3^{29}\mod(31)$
- Now you can solve $3^{29}\mod(31)$ using fast exponentiation method.
  


**** TODO Compute  $3^{-592} \mod(1831)$ using Fermat's Little Theorem


*** Code
#+begin_src python :results output raw :wrap src :exports both
def main():
    print(is_prime(31))

def is_prime(p):
    if (3**(p-1))%p == 1: # arbitrarily chose a=3
        return True
    return False

main()
    

#+end_src

#+RESULTS:
#+begin_src
True
#+end_src

** Euler's Theorem
#+begin_quote
$a^{\phi(n)} \equiv 1\mod(n)$, if
- $a$ and $n$ are coprime numbers
- $\phi(n)$ is the Euler's Phi Function
#+end_quote

*** Examples

**** Find $6^{24} \mod(35)$ using Euler's Theorem
- gcd(6,35) = 1, hence they are coprime
- $\phi(35) = \phi(5) \times \phi(7) = 4 \times 6 = 24$
- Hence $6^{24} \mod(35) \equiv 1\mod(35)$

**** Find $37^{103}\mod(40)$ using Euler's theorem
- $37^{\phi(40)}\mod(40) = 37^{\phi(2^{3}) \times \phi(5)}\mod(40) = 37^{16}\mod(40)$
- So according to euler's theorem, $37^{16} \equiv 1\mod(40)$
- $103 = 6\cdot16 + 7$
- So $(37^{16\times6 + 7}) \equiv 1\mod(40)$
- So $(37^{16})^{6} \times 37^{7} \equiv 1^{6} \times 37^{7}\mod(40)$
- Now the problem reduces to $37^{7}\mod(40)$
- We also know that $37\mod(40)$ is the same as $-3\mod(40)$ 
- So $(-3)^{7} \mod(40) = -1 \times 3^{7}\mod(40)$
- Now you can use fast exponentiation method (you could have used it for 37
  directly too, but this is better).

**** Find $71^{-1}\mod(100)$ using Euler's Theorem
- gcd(71, 100) = 1, hence they are coprime
- $\phi(100) = \phi(5^{2} \times 2^{2}) = 20 \times 2 = 40$
- $71^{40} \mod 100 = 1$
- Find: $71^{39} \mod 100$
- $71^{1} \mod 100 = 71$
- $71^{2} \mod 100 = 41$
- $71^{4} \mod 100 = 81$
- $71^{8} \mod 100 = 61$
- $71^{16} \mod 100 = 21$
- $71^{32} \mod 100 = 41$
- $71^{32+4+2+1} \mod 100 = 41\times81\times41\times71 \mod 100$

**** Find $8^{-1} \mod(77)$

** Discrete Logarithm
