#+title: Mobile Application Development 
#+SETUPFILE: /home/praaneshnair/.config/doom/templates/org/html-preamble.org


* Prelude
- These notes don't include Android Studio tutorials as:
  1. Graphical tutorials are a lot of effort
  2. Android Studio keeps evolving so it's going to be different when you're
     reading this.
- Unlike most of my other notes, these should be used as complementary material.
  I really don't think these notes can replace lectures or a course itself.

* Introduction to Android

** User Interaction
*** Touch Gestures
- Swiping
- Tapping
- Pinching
  
*** Virtual Keyboard
- Characters
- Numbers
- Emojis

*** External
- Bluetooth
- USB controllers
- Peripherals

** Android Stack

| System Apps ~OR~ User Apps                      |
| Java API Framework                            |
| Native C/C++ Runtime ~OR~ Android Runtime (ART) |
| Hardware Abstraction Layer                    |
| Linux Kernel                                  |

- Every layer in this stack, uses services of the layer below, to serve the
  layer above.
- The linux kernel is responsible for low-level memory management and security
  features.
- The kernel talks to the hardware directly, and hardware abstraction layer
  makes accessing hardware more abstract and standardized.
- Native C/C++ libraries (Android Native Development Kit, or NDK) or Android
  Runtime (ART), do all the backend work involved in an app. These include
  managing databases, graphics, web rendering engines, and in basic system
  functions too.
- The Java API Framework consists of premade classes which correspond to
  different parts of an app.

  
** Android Application Components

| Component         | What it is                                                      |
|-------------------+-----------------------------------------------------------------|
| ~Activity~          | A visible screen                                                |
| ~Service~           | Background work                                                 |
| ~Intent~            | A message/request                                               |
| ~BroadcastReceiver~ | Listens to system level broadcast messages (like "battery low") |
| ~ContentProvider~   | Data Management                                                 |


* How the App works

** Activity
- A Java Class that serves as a controller for a specific screen, is called an
  activity.
- Such a Java Class must ~extend Activity~ (basic [[https://developer.android.com/guide/components/activities/activity-lifecycle][activity lifecycle]] features
  provided here) or ~extend AppCompatActivity~ (this is preferred because modern
  Android features are backported to older versions too). ~AppCompatActivity~
  extends ~FragmentActivity~ which extends ~ComponentActivity~ which extends
  ~Activity~.
- The screen that the app starts with, is controlled with the help of the
  ~MainActivity.java~ file.


** XML Files
- All of the components of the UI of a particular screen is created using an XML
  file or a group of XML files.
- Such a component is called a *view*.
- Examples of views include ~TextView~ (for displaying text), ~EditText~ (for taking
  text input), ~RadioButton~, ~Switch~, ~SeekBar~ (sliders), etc.
- Each view will have an ~id~ (an integer), which can be accessed in a Java Class
  as ~R.id.nameOfID~, where ~R~ is a ~final class~ created by Android at build time.
- An activity is connected to the XML layout because of a line that looks like:
  #+begin_src java
setContentView(R.layout.activity_main);
  #+end_src
  where ~activity_main.xml~ is the name of the xml file.

*** ~<TextView/>~
Let's arbitrarily take the ~<TextView/>~ view and study its properties.
#+begin_src java
<TextView
       android:id="@+id/nameOfID"
       android:layout_width="match_parent"
       android:layout_height="wrap_content"
       android:background="@color/myBackgroundColor"
       android:text="@string/count_initial_value"
       android:textColor="@color/#0000aa"
       android:textSize="@dimen/count_text_size"
       android:gravity="center"
       android:textAlignment="center"
       android:textStyle="bold" 
/>
#+end_src

**** ~layout_width~ or ~layout_height~

| Value            | Meaning                                     |
|------------------+---------------------------------------------|
| ~wrap_content~     | Only as wide as the text                    |
| ~100dp~            | Fixed width                                 |
| ~0dp~              | Used with ~layout_weight~ or ConstraintLayout |
| ~match_constraint~ | ConstraintLayout only                       |

~dp~ (density-independent pixels) are used for layout dimensions, while ~sp~
(scale-independent pixels) are used for text-sizes.


* Basic Addition
- This code follows from [[https://www.youtube.com/watch?v=4hEsnJPoP4s][this video]].
- First declare private variables in the ~MainActivity~ class:
  #+begin_src java
private EditText num1, num2;
private Button add;
private TextView result;
  #+end_src
  Make sure you do ~alt + enter~ when your mouse is over the ~EditText~, ~Button~ or
  ~TextView~ datatype, to resolve all imports.
- Next, in the end of ~onCreate()~ function, get all of views using their IDs
  ~R.id.idName~, and then assign them to the private variables you created:
  #+begin_src java
num1 = (EditText) findViewById(R.id.no1);
num2 = (EditText) findViewById(R.id.no2);
result = (TextView) findViewById(R.id.result);
add = (Button) findViewById(R.id.addButton);
  #+end_src
  Before assigning, make sure you appropriately typecast the View.
- To the button object ~add~, use the ~setOnClickListener()~ method as
  ~add.setOnClickListener();~. Inside, add a parameter that starts from ~new View~
  and just pick the first suggestion (it's most likely what we need). So the
  function will look like this:
  #+begin_src java
addButton.setOnClickListener(new View.OnClickListener() {
    @Override
    public void onClick(View v) {
        // here is where we do the logic
    }
});

  #+end_src
- Use the ~setText~ method on the ~result~ TextView. It can only take a String, so
  typecast whatever you want to show using ~String.valueOf()~.
  #+begin_src java
add.setOnClickListener(new View.OnClickListener() {
    @Override
    public void onClick(View v) {
        result.setText(String.valueOf(
                Integer.parseInt(num1.getText().toString())
                + Integer.parseInt(num2.getText().toString())
        ));
    }
});

  #+end_src
 Just try typing whatever is inside, all you need to do is tab your way through.
  
  
  
- The complete app looks like this:
  #+begin_src java
public class MainActivity extends AppCompatActivity {
    // declare these variables
    private EditText num1, num2;
    private Button add;
    private TextView result;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        // some code already here, just add the below code

        num1 = (EditText) findViewById(R.id.no1);
        num2 = (EditText) findViewById(R.id.no2);
        result = (TextView) findViewById(R.id.result);
        add = (Button) findViewById(R.id.addButton);
        add.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                result.setText(String.valueOf(
                        Integer.parseInt(num1.getText().toString())
                        + Integer.parseInt(num2.getText().toString())
                ));
            }
        });

    }
}
  #+end_src

* Rerouting to a different screen using Intent
- Right click on the ~app~ and create a new activity (android studio will
  automatically create and link the XML file).
- Trigger the new activity by setting onClick parameter as the name of a
  function ~doSomething()~, which is a void function defined in ~MainActivity~.
  #+begin_src java
public void doSomething(View view){
    Intent intent = new Intent(this, Next.class);
    intent.putExtra("answer", String.valueOf(Integer.parseInt(someInput.getText().toString()) +100));
    startActivity(intent);
}

  #+end_src
  where ~someInput~ is the id of an ~EditText~ object.
- And in the new activity's ~onCreate()~ function:
  #+begin_src java
Intent intent = getIntent();
textView = (TextView) findViewById(R.id.textView);
textView.setText(String.valueOf(intent.getStringExtra("answer")));

  #+end_src
  
* Scroll View
- When you use scroll view, drag and drop a linear layout into the component
  tree, and then put whatever you want in there.
- Drag and drop only into the component tree (bottom left corner, basically
  under palette), because all Views should be under the linear layout.

* Spinner
- Just add Spinner into the XML, and then in the ~onCreate()~ function:
  #+begin_src java
List<String> spinnerList = new ArrayList<>();
spinnerList.add("Item 1");
spinnerList.add("Item 2");
spinnerList.add("Item 3");
spinnerList.add("Item 4");

Spinner spinner = findViewById(R.id.spinner);

ArrayAdapter<String> adapter = new ArrayAdapter<>(this, android.R.layout.simple_spinner_item, spinnerList);
adapter.setDropDownViewResource(android.R.layout.simple_spinner_dropdown_item);
spinner.setAdapter(adapter);
  #+end_src

* Feedback app

** RatingBar
- You get the rating as:
  #+begin_src java
float rating = ratingBar.getRating();
  #+end_src
** Radio Button
- Given:
  #+begin_src java
difficulty = findViewById(R.id.difficulty);
  #+end_src
  then the selected radio button is obtained through the id (int):
  #+begin_src java
int selectedId = difficulty.getCheckedRadioButtonId();
  #+end_src
** CheckBox
#+begin_src java
recommendCheckBox = findViewById(R.id.recommend);
#+end_src
You check if it's checked or not by the boolean return value:
#+begin_src java
boolean recommend = recommendCheckBox.isChecked();
#+end_src
** Making a WebSearch Button
#+begin_src java
Intent intent = new Intent(Intent.ACTION_WEB_SEARCH);
intent.putExtra(SearchManager.QUERY, topic);
startActivity(intent);
#+end_src
** Solving Data Loss after Screen Rotation
*** What happens when screen rotates
#+begin_src java
    @Override
    protected void onSaveInstanceState(@NonNull Bundle outState) {
        super.onSaveInstanceState(outState);
        // the below line is what you add
        outState.putString("topic", feedbackTopic.getText().toString());
    }
#+end_src
When you rotate the screen, the state of an activity is destroyed. This is the
function that's called just before the activity is destroyed.

*** What happens after screen rotates
#+begin_src java
    @Override
    protected void onRestoreInstanceState(@NonNull Bundle savedInstanceState) {
        super.onRestoreInstanceState(savedInstanceState);
        // the below line is what you add
        feedbackTopic.setText(savedInstanceState.getString("topic"));
    }

#+end_src
This is the function that is called when the activity is recreated after the
screen rotates.

